###
GET http://localhost:5000/api/product HTTP/1.1
###
POST http://localhost:5000/api/user/register HTTP/1.1
content-type: application/json

{
    "email": "alisalehni@fh.com",
    "password": "98989898989",
    "name":"wahed m",
    "phoneNumber":"07882471700"
}
###
POST http://localhost:5000/api/user/login HTTP/1.1
content-type: application/json

{
    "email": "wahedm@gma3il9.com",
    "password": "1234579444"
}
###

GET http://localhost:5000/api/product/seed HTTP/1.1
content-type: application/json
