import product from './assets/p1.jfif'
export const products = [
    {
        id: 1,
        name: "winter body",
        descripthion: [
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
        ],
        price: 120,
        offPrice: 120,
        discount: 0,
        image: product,
    },
    {
        id: 2,
        name: "winter body",
        descripthion: [
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
        ],
        price: 120,
        offPrice: 120,
        discount: 0,
        image: product,
    },
    {
        id: 3,
        name: "winter body",
        descripthion: [
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
        ],
        price: 120,
        offPrice: 110,
        discount: 0,
        image: product,
    },
    {
        id: 4,
        name: "winter body",
        descripthion: [
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
        ],
        price: 120,
        offPrice: 120,
        discount: 0,
        image: product,
    },
    {
        id: 5,
        name: "winter body",
        descripthion: [
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
        ],
        price: 120,
        offPrice: 100,
        discount: 0,
        image: product,
    },
    {
        id: 6,
        name: "winter body",
        descripthion: [
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
            { support: "گارانتی مادام العمر" },
        ],
        price: 120,
        offPrice: 90,
        discount: 0,
        image: product,
    },
]